name:                check-cgminer
version:             0.7.7.0
github:              "dmp1ce/check_cgminer"
license:             PublicDomain
author:              "David Parrish"
maintainer:          "daveparrish@tutanota.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Monitoring plugin for cgminer devices
category:            Monitoring

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dmp1ce/check_cgminer#readme>

dependencies:
- base >= 4.7 && < 5
- nagios-check
- optparse-applicative
- text
- network-simple
- aeson
- bytestring
- monad-loops
- containers
- vector
- scientific
- wreq
- lens
- lens-aeson
- cereal
- directory
- filepath
- time

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - ScopedTypeVariables

library:
  source-dirs: src
  ghc-options: -Wall -Werror -O2

_ghc-options: &ghc-options
  - -Wall
  - -Werror
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  check_cgminer:
    main:                Main.hs
    source-dirs:         app
    ghc-options: *ghc-options
    dependencies:
    - check-cgminer

tests:
  check-cgminer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: *ghc-options
    dependencies:
    - check-cgminer
    - tasty
    - tasty-hunit
